apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: api-gateway
  namespace: health-platform-prod
  labels:
    app.kubernetes.io/part-of: healthecosystem
spec:
  host: prod-api-gateway.health-platform-prod.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1000
      http:
        h2UpgradePolicy: UPGRADE
        http1MaxPendingRequests: 500
        http2MaxRequests: 2000
        maxRequestsPerConnection: 100
    loadBalancer:
      simple: LEAST_REQUEST
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 60s
      maxEjectionPercent: 30
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: lims-service
  namespace: health-platform-prod
  labels:
    app.kubernetes.io/part-of: healthecosystem
spec:
  host: prod-lims-service.health-platform-prod.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 2000
      http:
        http1MaxPendingRequests: 1000
        http2MaxRequests: 5000
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 20s
      baseEjectionTime: 30s
      maxEjectionPercent: 20
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary
