apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: health-platform
  labels:
    app.kubernetes.io/name: identity-service
    app.kubernetes.io/part-of: healthecosystem
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: identity-service
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: health-platform
  labels:
    app.kubernetes.io/name: patient-service
    app.kubernetes.io/part-of: healthecosystem
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: patient-service
  ports:
    - name: http
      port: 3003
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: lims-service
  namespace: health-platform
  labels:
    app.kubernetes.io/name: lims-service
    app.kubernetes.io/part-of: healthecosystem
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lims-service
  ports:
    - name: http
      port: 3004
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: health-platform
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: healthecosystem
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api-gateway
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
